math = false

[daisy]
  subtitle     = '不乱于心，不困于情；不畏将来，不念过往'
  description  = '欲望要简单，待人要真诚，扮好每个角色'
  mes_404      = 'Over the Mountains, mountains...'
  scroll_title = true
  [daisy.author]
    name = 'Qihuan Liu'
    avatar = "/images/avatar.jpg"
    homepage = "https://daisilia.com/"
  [daisy.related]
    enable=false
  [daisy.comment]
    enable            = true
    disable_on_local  = true
    repo              = 'alohaia/alohaia.github.io'
    repo_id           = 'MDEwOlJlcG9zaXRvcnkzNjgxNjY5NTY='
    category          = "Announcements"
    category_id       = "DIC_kwDOFfHILM4B_XeA"
    mapping           = "title"
    reactions_enabled = "1"
    emit_metadata     = "1"
    theme             = "light"
  [daisy.pjax]
    enable = true
  [daisy.fancybox]
    enable = true
  [daisy.exturl]
    enable = false
  # sidebar
  [daisy.social]
    github = "https://github.com/alohaia"
    email = "liu.qihuan@outlook.com"
    bilibili = "https://space.bilibili.com/437854288"
  [daisy.links]
    "**郭老师**的网络自留地" = "https://www.sdiopid.top"
  [daisy.calendar]
    enable = true
  [daisy.quote]
    enable = 'jinrishici' # or 'rainbow'
  [daisy.music]
    enable      = false
    server      = 'netease'
    type        = 'playlist'
    id          = '6822976600'
    mini        = false
    fixed       = false
    list_folded = true
    autoplay    = false
    volume      = 0.4
    theme       = '#b7daff'
    order       = 'random'
    loop        = 'all'
    preload     = 'auto'
    mutex       = true
  [daisy.footer]
    enable = ["poweredby", "copyright", "creativecommons"]
  [daisy.footer.copyright]
    startyear = 2020
    icon = '''<span class="heart animate__heartBeat animate__infinite"><i class="fas fa-heart"></i></span>'''
  [daisy.footer.creativecommons]
    scheme = "by-nc-sa"
    lang = "deed.zh"
